

services:
  haserl-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: haserl-app
    ports:
      - "8080:80"
    volumes:
      - ./app/index.cgi:/var/www/localhost/cgi-bin/index.cgi
      - ./app/style.css:/var/www/localhost/htdocs/style.css
      - ./app/test.html:/var/www/localhost/htdocs/test.html
      - ./logs:/var/log
    restart: unless-stopped
    environment:
      - TZ=UTC
    networks:
      - haserl-network

networks:
  haserl-network:
    driver: bridge